#!/bin/bash

. "${HOME}/.cache/wal/colors.sh"

swaynag -t warning --font 'JetBrains Mono' --border-bottom $color2 --border-bottom-size 3 --background "$color0"F0 --border $color2 --button-background $color0 --text $color7 \
	-m 'You pressed the power button.' \
	-b 'poweroff' 'systemctl poweroff' \
	-b 'hibernate' 'systemctl hibernate' \
	-b 'reboot' 'systemctl reboot' \
	-b 'suspend' 'systemctl suspend' \
	-b 'exit sway' 'swaymsg exit' \
	-s 'abort'
